name: Deplot fastapi-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


job: 
 build:
  runs-on: ubuntu-latest
 sets:
 - name: checkout
   uses: actions/checkout@v3
 - name: set up python 3.9
   uses: actions/setup-python@v4
   with:
     python-version: '3.9'
 - name: install dependencies
   run:
    python -m pip install --upgrade pip
    pip install -r requirements.txt
 - name: login to dockerhub
   uses: docker/login-action@v1
   with:
     username: havi98
     password: dckr_pat_eE9z0ifb3P4RJE9J_UNOENJYjkY
 - name: build on release to dockerhub
   run:
     docker build -t havi98/fastapi_1101:latest .
     docker push havi98/fastapi_1101:latest

		
		
